### ISSUE TITLE
Mirrored NIRCam FoV?

### ISSUE THREAD

**Issue by tfish13** [spacetelescope/jwst_footprints#9]
Hi there, the NIRCam FoV w/ FULL3 dither pattern created by this tool appears to be mirrored from what is shown in APT/Aladdin. 

<img width="1154" alt="Screen Shot 2020-11-22 at 2 32 15 PM" src="https://user-images.githubusercontent.com/7915472/99926709-8fc96800-2d10-11eb-81f0-a7bc8d011a80.png">

**Comment by ewislowski** [comment]
Hi @tfish13, thanks so much for reporting this issue. It should be fixed in version 2.5.0, released today.
